[[redirects]]
  from = "/proxy/*"
  to = "https://Jjolab-env4.eba-qqth2vcp.ap-northeast-2.elasticbeanstalk.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false